/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaacademico;

import javax.swing.JOptionPane;
import javax.swing.JTabbedPane;
import jdk.nashorn.internal.runtime.Debug;

/**
 *
 * @author leofe_qbel5qv
 */
public class Menu_Principal extends javax.swing.JFrame {

    /**
     * Creates new form Menu_principal
     */
    public Menu_Principal() { 
        Debug_SA.create_database();
        initComponents();
        jPopupMenuAluno.add(this.Menu_Aluno);
        jPopupMenuProfessor.add(this.Menu_Professor);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPopupMenuAluno = new javax.swing.JPopupMenu();
        Menu_Aluno = new javax.swing.JPanel();
        btn_Remover_Aluno = new javax.swing.JButton();
        btn_Alterar_Aluno = new javax.swing.JButton();
        jPopupMenuProfessor = new javax.swing.JPopupMenu();
        Menu_Professor = new javax.swing.JPanel();
        btn_Remover_Professor = new javax.swing.JButton();
        btn_Alterar_Professor = new javax.swing.JButton();
        jPanel1 = new javax.swing.JPanel();
        tbd = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_alunos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        btn_Adicionar_Aluno = new javax.swing.JButton();
        btn_Remover_Tudo_Aluno = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        tbl_professores = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        btn_Adicionar_Professor = new javax.swing.JButton();
        btn_Remover_Tudo_Professor = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        btn_Remover_Tudo = new javax.swing.JButton();
        jLabel4 = new javax.swing.JLabel();

        btn_Remover_Aluno.setText("Remover");
        btn_Remover_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Remover_AlunoActionPerformed(evt);
            }
        });

        btn_Alterar_Aluno.setText("Alterar");
        btn_Alterar_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Alterar_AlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_AlunoLayout = new javax.swing.GroupLayout(Menu_Aluno);
        Menu_Aluno.setLayout(Menu_AlunoLayout);
        Menu_AlunoLayout.setHorizontalGroup(
            Menu_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(Menu_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Menu_AlunoLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(Menu_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_Alterar_Aluno, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Remover_Aluno, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        Menu_AlunoLayout.setVerticalGroup(
            Menu_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
            .addGroup(Menu_AlunoLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Menu_AlunoLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(btn_Remover_Aluno)
                    .addGap(18, 18, 18)
                    .addComponent(btn_Alterar_Aluno)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        btn_Remover_Professor.setText("Remover");
        btn_Remover_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Remover_ProfessorActionPerformed(evt);
            }
        });

        btn_Alterar_Professor.setText("Alterar");
        btn_Alterar_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Alterar_ProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout Menu_ProfessorLayout = new javax.swing.GroupLayout(Menu_Professor);
        Menu_Professor.setLayout(Menu_ProfessorLayout);
        Menu_ProfessorLayout.setHorizontalGroup(
            Menu_ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 100, Short.MAX_VALUE)
            .addGroup(Menu_ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Menu_ProfessorLayout.createSequentialGroup()
                    .addGap(12, 12, 12)
                    .addGroup(Menu_ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btn_Alterar_Professor, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btn_Remover_Professor, javax.swing.GroupLayout.Alignment.TRAILING))
                    .addContainerGap(13, Short.MAX_VALUE)))
        );
        Menu_ProfessorLayout.setVerticalGroup(
            Menu_ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 93, Short.MAX_VALUE)
            .addGroup(Menu_ProfessorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(Menu_ProfessorLayout.createSequentialGroup()
                    .addGap(18, 18, 18)
                    .addComponent(btn_Remover_Professor)
                    .addGap(18, 18, 18)
                    .addComponent(btn_Alterar_Professor)
                    .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
        );

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbd.setBackground(new java.awt.Color(204, 204, 204));
        tbd.setBorder(javax.swing.BorderFactory.createLineBorder(new java.awt.Color(0, 0, 0)));
        tbd.addChangeListener(new javax.swing.event.ChangeListener() {
            public void stateChanged(javax.swing.event.ChangeEvent evt) {
                tbdStateChanged(evt);
            }
        });

        jPanel2.setBackground(new java.awt.Color(255, 102, 102));

        tbl_alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Nome", "Curso", "Endereço", "Telefone", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_alunos.setComponentPopupMenu(jPopupMenuAluno);
        jScrollPane1.setViewportView(tbl_alunos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Gerenciar Alunos");

        btn_Adicionar_Aluno.setText("Adicionar");
        btn_Adicionar_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Adicionar_AlunoActionPerformed(evt);
            }
        });

        btn_Remover_Tudo_Aluno.setText("Remover Tudo");
        btn_Remover_Tudo_Aluno.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Remover_Tudo_AlunoActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Remover_Tudo_Aluno)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Adicionar_Aluno)
                        .addGap(12, 12, 12)))
                .addContainerGap())
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(361, 361, 361)
                .addComponent(jLabel1)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(btn_Adicionar_Aluno)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Remover_Tudo_Aluno)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        tbd.addTab("Alunos", jLayeredPane1);

        jPanel3.setBackground(new java.awt.Color(204, 255, 153));

        tbl_professores.setBackground(new java.awt.Color(204, 255, 204));
        tbl_professores.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registro", "Nome", "Matéria", "Endereço", "Telefone", "Sexo"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        tbl_professores.setComponentPopupMenu(jPopupMenuProfessor);
        tbl_professores.setGridColor(new java.awt.Color(204, 204, 255));
        jScrollPane2.setViewportView(tbl_professores);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Gerenciar Professores");

        btn_Adicionar_Professor.setText("Adicionar");
        btn_Adicionar_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Adicionar_ProfessorActionPerformed(evt);
            }
        });

        btn_Remover_Tudo_Professor.setText("Remover Tudo");
        btn_Remover_Tudo_Professor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Remover_Tudo_ProfessorActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 846, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btn_Remover_Tudo_Professor)
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_Adicionar_Professor)
                        .addGap(14, 14, 14)))
                .addContainerGap())
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(345, 345, 345)
                .addComponent(jLabel2)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(btn_Adicionar_Professor)
                        .addGap(18, 18, 18)
                        .addComponent(btn_Remover_Tudo_Professor)
                        .addGap(0, 0, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 348, Short.MAX_VALUE))
                .addContainerGap())
        );

        tbd.addTab("Professores", jPanel3);

        btn_Remover_Tudo.setText("Limpar BD");
        btn_Remover_Tudo.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btn_Remover_TudoActionPerformed(evt);
            }
        });

        jLabel4.setText("Deleta todos os itens do banco de dados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(50, 50, 50)
                .addComponent(btn_Remover_Tudo)
                .addGap(28, 28, 28)
                .addComponent(jLabel4)
                .addContainerGap(637, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(42, 42, 42)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btn_Remover_Tudo)
                    .addComponent(jLabel4))
                .addContainerGap(341, Short.MAX_VALUE))
        );

        tbd.addTab("DEBUG", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(tbd)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(tbd))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btn_Adicionar_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Adicionar_AlunoActionPerformed
        // TODO add your handling code here:
        Formulario_Register_Aluno f = new Formulario_Register_Aluno();
        f.setVisible(true);
    }//GEN-LAST:event_btn_Adicionar_AlunoActionPerformed
    
    private void btn_Alterar_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Alterar_AlunoActionPerformed
        // TODO add your handling code here:
        try{
            
            int fila = tbl_alunos.getSelectedRow();

            Formulario_Update_Aluno f = new Formulario_Update_Aluno();
            f.lblRA.setText(tbl_alunos.getValueAt(fila, 0).toString());
            f.txtNome.setText(tbl_alunos.getValueAt(fila, 1).toString());
            f.txtCurso.setText(tbl_alunos.getValueAt(fila, 2).toString());
            f.txtEndereco.setText(tbl_alunos.getValueAt(fila, 3).toString());
            f.txtTelefone.setText(tbl_alunos.getValueAt(fila, 4).toString());
            f.txtSexo.setText(tbl_alunos.getValueAt(fila, 5).toString());
            f.setVisible(true);
        }catch(Exception e){
            System.out.println("nenhuma linha selecionada");
        }
    }//GEN-LAST:event_btn_Alterar_AlunoActionPerformed

    private void btn_Remover_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Remover_AlunoActionPerformed
        // TODO add your handling code here:
        try{
            int fila = tbl_alunos.getSelectedRow();

            Sentenca_Aluno s = new Sentenca_Aluno();

            s.setRA(tbl_alunos.getValueAt(fila, 0).toString());

            if(Funcoes_Aluno.isDelete(s)){
                Funcoes_Aluno.setListar("");
                JOptionPane.showMessageDialog(this, "Registro Eliminado com Sucesso", "INFORMAÇÂO", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao Eliminar Registro", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println("nenhuma linha selecionada");
        }
    }//GEN-LAST:event_btn_Remover_AlunoActionPerformed

    private void btn_Remover_TudoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Remover_TudoActionPerformed
        // TODO add your handling code here:
        Debug_SA.Delete_All();
    }//GEN-LAST:event_btn_Remover_TudoActionPerformed

    private void btn_Remover_Tudo_AlunoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Remover_Tudo_AlunoActionPerformed
        // TODO add your handling code here:
        Object[] options = { "Sim", "Cancelar" };
        int opt = JOptionPane.showOptionDialog(null, "Tem certeza que deseja deletar TODOS os alunos?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if(opt==1){
            return;
        }
        
        Sentenca_Aluno s = new Sentenca_Aluno();
        
        if(Funcoes_Aluno.isTruncate(s)){
            Funcoes_Aluno.setListar("");
            JOptionPane.showMessageDialog(this, "Registros Eliminados com Sucesso", "INFORMAÇÂO", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao Eliminar os Registros", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_Remover_Tudo_AlunoActionPerformed

    private void btn_Adicionar_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Adicionar_ProfessorActionPerformed
        // TODO add your handling code here:
        Formulario_Register_Professor f = new Formulario_Register_Professor();
        f.setVisible(true);
    }//GEN-LAST:event_btn_Adicionar_ProfessorActionPerformed

    private void btn_Remover_Tudo_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Remover_Tudo_ProfessorActionPerformed
        // TODO add your handling code here:
        Object[] options = { "Sim", "Cancelar" };
        int opt = JOptionPane.showOptionDialog(null, "Tem certeza que deseja deletar TODOS os professores?", "Informação", JOptionPane.DEFAULT_OPTION, JOptionPane.WARNING_MESSAGE, null, options, options[0]);
        if(opt==1){
            return;
        }
        
        Sentenca_Professor s = new Sentenca_Professor();
        
        if(Funcoes_Professor.isTruncate(s)){
            Funcoes_Professor.setListar("");
            JOptionPane.showMessageDialog(this, "Registros Eliminados com Sucesso", "INFORMAÇÂO", JOptionPane.INFORMATION_MESSAGE);
        }else{
            JOptionPane.showMessageDialog(this, "Erro ao Eliminar os Registros", "ERRO", JOptionPane.ERROR_MESSAGE);
        }
    }//GEN-LAST:event_btn_Remover_Tudo_ProfessorActionPerformed

    private void btn_Remover_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Remover_ProfessorActionPerformed
        // TODO add your handling code here:
        try{
            int fila = tbl_professores.getSelectedRow();

            Sentenca_Professor s = new Sentenca_Professor();

            s.setRegistro(tbl_professores.getValueAt(fila, 0).toString());

            if(Funcoes_Professor.isDelete(s)){
                Funcoes_Professor.setListar("");
                JOptionPane.showMessageDialog(this, "Registro Eliminado com Sucesso", "INFORMAÇÂO", JOptionPane.INFORMATION_MESSAGE);
            }else{
                JOptionPane.showMessageDialog(this, "Erro ao Eliminar Registro", "ERRO", JOptionPane.ERROR_MESSAGE);
            }
        }catch(Exception e){
            System.out.println("nenhuma linha selecionada");
        }
    }//GEN-LAST:event_btn_Remover_ProfessorActionPerformed

    private void btn_Alterar_ProfessorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btn_Alterar_ProfessorActionPerformed
        // TODO add your handling code here:
        try{  
            int fila = tbl_professores.getSelectedRow();

            Formulario_Update_Professor f = new Formulario_Update_Professor();
            f.lblRegistro.setText(tbl_professores.getValueAt(fila, 0).toString());
            f.txtNome.setText(tbl_professores.getValueAt(fila, 1).toString());
            f.txtMateria.setText(tbl_professores.getValueAt(fila, 2).toString());
            f.txtEndereco.setText(tbl_professores.getValueAt(fila, 3).toString());
            f.txtTelefone.setText(tbl_professores.getValueAt(fila, 4).toString());
            f.txtSexo.setText(tbl_professores.getValueAt(fila, 5).toString());
            f.setVisible(true);
        }catch(Exception e){
            System.out.println("nenhuma linha selecionada");
        }
    }//GEN-LAST:event_btn_Alterar_ProfessorActionPerformed

    private void tbdStateChanged(javax.swing.event.ChangeEvent evt) {//GEN-FIRST:event_tbdStateChanged
        // TODO add your handling code here:
        JTabbedPane sourceTabbedPane = (JTabbedPane) evt.getSource();
        int index = sourceTabbedPane.getSelectedIndex();
        String tbd_title = sourceTabbedPane.getTitleAt(index);
        if( "Alunos".equals(tbd_title) ){
            Funcoes_Aluno.setListar("");
        }else if("Professores".equals(tbd_title)){
            Funcoes_Professor.setListar("");
        }
    }//GEN-LAST:event_tbdStateChanged

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_Principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menu_Principal().setVisible(true);
            }
        });
        
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JPanel Menu_Aluno;
    private javax.swing.JPanel Menu_Professor;
    private javax.swing.JButton btn_Adicionar_Aluno;
    private javax.swing.JButton btn_Adicionar_Professor;
    private javax.swing.JButton btn_Alterar_Aluno;
    private javax.swing.JButton btn_Alterar_Professor;
    private javax.swing.JButton btn_Remover_Aluno;
    private javax.swing.JButton btn_Remover_Professor;
    private javax.swing.JButton btn_Remover_Tudo;
    private javax.swing.JButton btn_Remover_Tudo_Aluno;
    private javax.swing.JButton btn_Remover_Tudo_Professor;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPopupMenu jPopupMenuAluno;
    private javax.swing.JPopupMenu jPopupMenuProfessor;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane tbd;
    public static javax.swing.JTable tbl_alunos;
    public static javax.swing.JTable tbl_professores;
    // End of variables declaration//GEN-END:variables
}
