/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package sistemaacademico;

import BD.expressoes_BD;
import java.sql.Connection;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.SQLException;
import java.sql.Statement;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import sistemaacademico.Aluno;
import BD.AlunoDAO;
import sistemaacademico.Professor;

/**
 *
 * @author leofe_qbel5qv
 */
public class Menu_principal extends javax.swing.JFrame {
    Aluno[] Alunos = new Aluno[40];
    Professor[] Professores = new Professor[10];
    public void Listar_Alunos(){
        Alunos = new Aluno[40];
        Connection conn = BD.Conexao.getConnection();
        Statement stmt = null;
        try{
            stmt = conn.createStatement();
            ResultSet rs = stmt.executeQuery("SELECT * FROM alunos ORDER BY nome");
            try{
                int i=0;
                while(rs.next()){
                    if(Alunos.length<i){
                        System.out.println("Alocando mais espaço para alunos no sistema...");
                        Alunos = Funcoes.maisAlunos(Alunos);
                    }
                    Aluno a = new Aluno();
                    a.setRA(rs.getInt("RA"));
                    a.setNome(rs.getString("nome"));
                    a.setCurso(rs.getString("curso"));
                    a.setEndereço(rs.getString("endereco"));
                    a.setTelefone(rs.getString("telefone"));
                    a.setSexo(rs.getString("sexo"));
                    Alunos[i] = a;
                    i++;
                }
            }catch(SQLException exselect){
                JOptionPane.showMessageDialog(null, exselect);
            }
        }catch(SQLException ex){
            JOptionPane.showMessageDialog(null,ex);
        }
    }
    private void LoadTable_Alunos(){
        Listar_Alunos();
        DefaultTableModel modelo = new DefaultTableModel(new Object[]{"RA","Nome","Curso"},0);
        for(int i=0;i<Alunos.length;i++){
            if(Alunos[i]!=null){
                System.out.print(Alunos[i].getRA()+";");
                Object linha[] = new Object[]{  Alunos[i].getRA(),
                                            Alunos[i].getNome(),
                                            Alunos[i].getCurso()
                };
                modelo.addRow(linha);
            }
        }
        System.out.println();
        tbl_alunos.setModel(modelo);
    }
    /**
     * Creates new form Menu_principal
     */
    public Menu_principal() { 
        initComponents();
        LoadTable_Alunos();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jTabbedPane1 = new javax.swing.JTabbedPane();
        jLayeredPane1 = new javax.swing.JLayeredPane();
        jPanel2 = new javax.swing.JPanel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tbl_alunos = new javax.swing.JTable();
        jLabel1 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jButton2 = new javax.swing.JButton();
        jButton3 = new javax.swing.JButton();
        jPanel3 = new javax.swing.JPanel();
        jScrollPane2 = new javax.swing.JScrollPane();
        jTable2 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();
        jButton4 = new javax.swing.JButton();
        jButton5 = new javax.swing.JButton();
        jButton6 = new javax.swing.JButton();
        jPanel4 = new javax.swing.JPanel();
        jButton7 = new javax.swing.JButton();
        jButton8 = new javax.swing.JButton();
        jLabel3 = new javax.swing.JLabel();
        jLabel4 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        tbl_alunos.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "RA", "Nome", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane1.setViewportView(tbl_alunos);

        jLabel1.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel1.setText("Gerenciar Alunos");

        jButton1.setText("Adicionar");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        jButton2.setText("Remover");
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });

        jButton3.setText("Alterar");
        jButton3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton3ActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton1)
                    .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel2Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel1)
                .addGap(188, 188, 188))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel1)
                .addGap(7, 7, 7)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(jButton2)
                        .addGap(18, 18, 18)
                        .addComponent(jButton3)
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addComponent(jScrollPane1, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jLayeredPane1.setLayer(jPanel2, javax.swing.JLayeredPane.DEFAULT_LAYER);

        javax.swing.GroupLayout jLayeredPane1Layout = new javax.swing.GroupLayout(jLayeredPane1);
        jLayeredPane1.setLayout(jLayeredPane1Layout);
        jLayeredPane1Layout.setHorizontalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );
        jLayeredPane1Layout.setVerticalGroup(
            jLayeredPane1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel2, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jTabbedPane1.addTab("Alunos", jLayeredPane1);

        jTable2.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "Registro", "Nome", "Curso"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Integer.class, java.lang.String.class, java.lang.String.class
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }
        });
        jScrollPane2.setViewportView(jTable2);

        jLabel2.setFont(new java.awt.Font("Tahoma", 0, 24)); // NOI18N
        jLabel2.setText("Gerenciar Professores");

        jButton4.setText("Adicionar");

        jButton5.setText("Remover");

        jButton6.setText("Alterar");

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(12, 12, 12)
                .addComponent(jScrollPane2, javax.swing.GroupLayout.DEFAULT_SIZE, 499, Short.MAX_VALUE)
                .addGap(18, 18, 18)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton4)
                    .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(jButton6, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(jButton5, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                .addContainerGap())
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(165, 165, 165))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel2)
                .addGap(7, 7, 7)
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addComponent(jButton4)
                        .addGap(18, 18, 18)
                        .addComponent(jButton5)
                        .addGap(18, 18, 18)
                        .addComponent(jButton6)
                        .addGap(0, 245, Short.MAX_VALUE))
                    .addComponent(jScrollPane2, javax.swing.GroupLayout.PREFERRED_SIZE, 0, Short.MAX_VALUE))
                .addContainerGap())
        );

        jTabbedPane1.addTab("Professores", jPanel3);

        jButton7.setText("Limpar BD");
        jButton7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton7ActionPerformed(evt);
            }
        });

        jButton8.setText("Criar");
        jButton8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton8ActionPerformed(evt);
            }
        });

        jLabel3.setText("Cria o banco de dados padrão para utilizar o programa");

        jLabel4.setText("Deleta todos os itens do banco de dados");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(49, 49, 49)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(jButton8, javax.swing.GroupLayout.PREFERRED_SIZE, 79, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jButton7))
                .addGap(28, 28, 28)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(jLabel3)
                    .addComponent(jLabel4))
                .addContainerGap(199, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addGap(47, 47, 47)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton8)
                    .addComponent(jLabel3))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jButton7)
                    .addComponent(jLabel4))
                .addContainerGap(309, Short.MAX_VALUE))
        );

        jTabbedPane1.addTab("DEBUG", jPanel4);

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 621, Short.MAX_VALUE)
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jTabbedPane1))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        cadastrarAluno();
        LoadTable_Alunos();
    }//GEN-LAST:event_jButton1ActionPerformed
    
    private void jButton3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton3ActionPerformed
        // TODO add your handling code here:
        int RA = Integer.parseInt(JOptionPane.showInputDialog("Digite o RA do Aluno..."));
        Aluno a = pesquisarAluno(RA);
        alterarAluno(a);
        LoadTable_Alunos();
    }//GEN-LAST:event_jButton3ActionPerformed

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        // TODO add your handling code here:
        int RA = Integer.parseInt(JOptionPane.showInputDialog("Digite o RA do Aluno..."));
        excluirAluno(RA);
        LoadTable_Alunos();
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jButton7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton7ActionPerformed
        // TODO add your handling code here:
        debug.Delete_All();
        LoadTable_Alunos();
    }//GEN-LAST:event_jButton7ActionPerformed

    private void jButton8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton8ActionPerformed
        // TODO add your handling code here:
        debug.create_database();
        LoadTable_Alunos();
    }//GEN-LAST:event_jButton8ActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Menu_principal.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                
                new Menu_principal().setVisible(true);
            }
        });
        
    }

    boolean cadastrarAluno() {
                Aluno a = new Aluno();
                int ver=0;
                do{
                    a.setRA(Integer.parseInt(JOptionPane.showInputDialog("Digite o RA do aluno")));
                    if(pesquisarAluno(a.getRA())!=null){
                        JOptionPane.showMessageDialog(null,"Já existe um aluno com este RA no sistema!");
                    }else{
                        ver=1;
                    }
                }while(ver!=1);
		a.setNome(JOptionPane.showInputDialog("Digite o nome do aluno"));
		a.setCurso(JOptionPane.showInputDialog("Digite o curso do aluno"));
		a.setEndereço(JOptionPane.showInputDialog("Digite o endereço do aluno"));
		a.setTelefone(JOptionPane.showInputDialog("Digite o telefone do aluno"));
                a.setSexo(Funcoes.setSexoMenu());
                
                for(int i=0;i<Alunos.length;i++){
                    if(Alunos[i]==null){
                            Alunos[i] = a;
                            AlunoDAO.create(a);
                            return true;
                    }
                }
                
                System.out.println("Alocando mais espaço para alunos no sistema...");
                Alunos = Funcoes.maisAlunos(Alunos);
                for(int i=0;i<Alunos.length;i++){
                    if(Alunos[i]==null){
                        Alunos[i] = a;
                        AlunoDAO.create(a);
                        return true;
                    }
                }
		return false;
	}
	boolean excluirAluno(int RA) { 
            Aluno a = pesquisarAluno(RA);
            if(a==null){
                return false;
            }
            if(BD.AlunoDAO.delete(a.getRA())==true){
                a=null;
                return true;
            }else{
                return false;
            }
        }
	boolean alterarAluno(Aluno a) {
            int i=0;
            int opt=0;
            Aluno original = new Aluno();//original armazena o item original para recuperação
            original.setRA(a.getRA());
            original.setNome(a.getNome());
            original.setCurso(a.getCurso());
            original.setEndereço(a.getEndereço());
            original.setTelefone(a.getTelefone());
            original.setSexo(a.getSexo());
            do{
               opt = Integer.parseInt(JOptionPane.showInputDialog("Selecione o que deseja alterar:\n1)-RA\n2)-Nome\n3)-Curso\n4)-Endereço\n5)-Telefone\n6)-Sexo\n\nDigite -1 para prosseguir"));
               switch(opt){
                    case -1://Mostra os dados alterados para que ocorra a confirmação
                        int confirma;
                        do{
                          confirma =Integer.parseInt(JOptionPane.showInputDialog("Tem certeza de que deseja prosseguir com as alterações? \n"
                          + "RA      :"+original.getRA()+" -> "+ a.getRA()+"\n"
                          + "Nome    :"+original.getNome()+" -> "+ a.getNome()+"\n"
                          + "Curso   :"+original.getCurso()+" -> "+ a.getCurso()+"\n"
                          + "Endereço:"+original.getEndereço()+" -> "+ a.getEndereço()+"\n"
                          + "Telefone:"+original.getTelefone()+" -> "+ a.getTelefone()+"\n"
                          + "Sexo:    "+original.getSexo()+" -> "+ a.getSexo()+"\n"
                          + "\n 1)-Sim  2)-Não 3)-Sair sem Alterar"));
                          switch(confirma){
                              case 1: break;
                              case 2: opt=0;break;//impede que o loop principal do menu (switch(opt)) termine
                              case 3: 
                                  a.setRA(original.getRA());
                                  a.setNome(original.getNome());
                                  a.setCurso(original.getCurso());
                                  a.setEndereço(original.getEndereço());
                                  a.setTelefone(original.getTelefone());
                                  a.setSexo(original.getSexo());
                                  return false;
                              default:JOptionPane.showMessageDialog(null, "A opção:"+confirma+" não existe!");break;
                          }
                        }while(confirma!=1&&confirma!=2);
                        break;
                    case  1:a.setRA(Integer.parseInt(JOptionPane.showInputDialog("Original:"+original.getRA()+"\nDigite o RA novo")));break;
                    case  2:a.setNome(JOptionPane.showInputDialog("Original:"+original.getNome()+"\nDigite o Nome novo"));break;
                    case  3:a.setCurso(JOptionPane.showInputDialog("Original:"+original.getCurso()+"\nDigite o Curso novo"));break;
                    case  4:a.setEndereço(JOptionPane.showInputDialog("Original:"+original.getEndereço()+"\nDigite o Endereço novo"));break;
                    case  5:a.setTelefone(JOptionPane.showInputDialog("Original:"+original.getTelefone()+"\nDigite o Telefone novo"));break;
                    case  6:
                        a.setSexo(Funcoes.setSexoMenu());
                        break;
                    default:JOptionPane.showMessageDialog(null, "A opção:"+opt+" não existe!");break;
               }
            }while(opt!=-1);
            
            return false;
	}
	Aluno pesquisarAluno(int RA) {
                for(int i=0;i<Alunos.length;i++){
                    if(Alunos[i]!=null){
                        if(Alunos[i].getRA()==RA){
                            return Alunos[i];
                        }
                    }
                }
                return null;
	}
    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JButton jButton3;
    private javax.swing.JButton jButton4;
    private javax.swing.JButton jButton5;
    private javax.swing.JButton jButton6;
    private javax.swing.JButton jButton7;
    private javax.swing.JButton jButton8;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLayeredPane jLayeredPane1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JScrollPane jScrollPane2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTable jTable2;
    private javax.swing.JTable tbl_alunos;
    // End of variables declaration//GEN-END:variables
}
